name: paz1dv
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter 
  google_fonts: ^6.3.0
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  animate_do: ^4.2.0
  responsive_framework: ^1.5.1
  hugeicons: ^0.0.11
  flutter_localizations:
     sdk: flutter
  intl: '>=0.19.0 <0.21.0'
  supabase_flutter: ^2.9.1
  rive: ^0.13.20
  audioplayers: ^6.5.0
  audioplayers_windows: ^4.2.1
  skeletonizer: ^2.1.0
dev_dependencies: 
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    
flutter_gen:
  output: lib/config/gen
  generate: true
  integrations:
    flutter_svg: true
